baseURL = "/"
languageCode = "en-us"
title = "NakSquad"
theme = "hugo-arcana"
copyright = "© Untitled. All rights reserved"

[taxonomies]
  category = "categories"
  tag = "tags"
  archive = "archives"

[params]
    description = "Naksquad.net"
    show_post_dates = false

    [[params.social]]
        title = "Twitter"
        icon = "fa-twitter"
        url = "#"
    [[params.social]]
        title = "Facebook"
        icon = "fa-facebook-f"
        url = "#"
    [[params.social]]
        title = "GitHub"
        icon = "fa-github"
        url = "#"
    [[params.social]]
        title = "LinkedIn"
        icon = "fa-linkedin-in"
        url = "#"
    [[params.social]]
        title = "Creative Commons"
        icon = "fa-creative-commons"
        url = "https://creativecommons.org/"


    [params.footer]

        [[params.footer.links]]
            header = "Links"

        [[params.footer.links.links]]
            title = "Link1"
            url = "#"

        [[params.footer.links.links]]
            title = "Get Teamspeak"
            url = "https://www.teamspeak.com/en/downloads/"

        [[params.footer.links]]

        [[params.footer.links.links]]
            title = "Link3"
            url = "#"            

        [[params.footer.links.links]]
            title = "Link4"
            url = "#"            

        [[params.footer.links.links]]
            title = "Link5"
            url = "#"            

        [params.footer.contact_form]
            enabled = false
            header = "Get In Touch"
            action = ""
