#[[main]]
#    name = "Servers"
#    weight = 30
#[[main]]
#    parent = "Servers"
#    name = "#1 Altis Invade and Annex"
#    url = "/servers/nak1"
#    weight = 31
#[[main]]
#    parent = "Servers"
#    name = "#2 Public Modded Zeus"
#   url = "/servers/nak2"
#    weight = 32
#[[main]]
#    parent = "Servers"
#   name = "#3 Tanoa Quicksilver"
#   url = "/servers/nak3"
#    weight = 33
#[[main]]
#   parent = "Servers"
#    name = "#4 Public Vanilla Zeus"
#  url = "/servers/nak4"
#   weight = 34
