baseURL = "https://axile.netlify.app/"
languageCode = "en-us"
title = "Naksquad"
theme = "axile"

[Params]
  icon = "https://github.com/Axorax/css-button-maker/blob/main/assets/img/axorax.png?raw=true"
  description = "Naksquad.net" # Site Description. Used in meta description
# Footer text, Each value will become a paragraph, Keep it as an array
  footerText = [ "---",
    "## Become part of the NAK Community.",
    "NAK Squad has been running gaming servers since 2016.",
    "Although much of our focus is on Arma 3, we explore new games as they are released with the intention of expanding the NAK community.",
    "We view NAK Squad as a family of members who are distributed all around the world.",
    "Our goal is to provide and promote a gaming environment that is safe for everyone.",
    "Along with our numerous game servers, we offer a TeamSpeak 3 server that provides a “Live Chatroom” for everyone to use.",
    "Using TeamSpeak will help improve your gaming experience and increases the sense of community.",
    "Welcome to NAK Squad and I hope to see you on our servers soon.",
    ]

[params.navbar]
patreon = "https://patreon.com/naksquad"


[params.navbarButton]
Donate = "https://patreon.com/naksquad"
