baseurl = "/"
title = "NakSquad"
languageCode = "en-us"
theme = "holy"
paginate = "10"
[Params]
  description = "Naksquad.net" # Site Description. Used in meta description
  opengraph = true # Enable OpenGraph if true
  schema = true # Enable Schema
  twitter_cards = false # Enable Twitter Cards if true
  columns = 2 # Set the number of cards columns. Possible values: 1, 2, 3
  mainSections = ["posts"] # Set main page sections
  dateFormat = "January 02, 2006" # Change the format of dates
  colorTheme = "dark-blue" # dark-green, dark-blue, dark-red, dark-violet
  #customCSS = ["css/custom.css"] # Include custom CSS files
  #customJS = ["js/custom.js"] # Include custom JS files
  mainMenuAlignment = "right" # Align main menu (desktop version) to the right side
  #authorbox = true # Show authorbox at bottom of single pages if true
  #comments = true # Enable comments for all site pages
  #related = false # Enable Related content for single pages
  #relatedMax = 5 # Set the maximum number of elements that can be displayed in related block. Optional
  #mathjax = true # Enable MathJax for all site pages
  #mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js" # Specify MathJax path. Optional
  #mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config. Optional
  #hideNoPostsWarning = false # Don't show no posts empty state warning in main page, if true