
[[main]]
  name = "Changes"
  url = "posts/"
  weight = -109

# Submenus are done this way: parent -> identifier
#[[main]]
#  name = "Links"
#  identifier = "Links"
#  weight = -108
#[[main]]
#  parent = "Links"
#  name = "LinkedIn"
#  url = "https://www.linkedin.com/"
#[[main]]
#  parent = "Links"
#  name = "Twitter"
#  url = "https://twitter.com/"

[[main]]
  name = "Servers"
  url = "servers/"
  weight = -107

# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/#"
[[social]]
  name = "twitter"
  weight = 2
  url = "https://twitter.com/#"
[[social]]
  name = "discord"
  weight = 3
  url = "https://discord.gg/#"
[[social]]
  name = "youtube"
  weight = 4
  url = "https://www.youtube.com/#"

# other supported social links
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"
# name = "linkedin"
# url = "https://www.linkedin.com/in/#"
# name = "rss"
# url = "index.xml"
